### PR TITLE
Dragonflight

### PR DESCRIPTION
**Pull request by ghost**
Add two new rares and rewards found while questing through The Waking Shores

### CODE REVIEW

**Comment by Dathwada** [comment]
These two "rares" should belong to bonus bosses, and the queen was already added (but your loot is new).

**Comment by Krovikan** [comment]
Say me if I do correct the movement of the bosses, please.


Regards

**Comment by Krovikan** [comment]
I think that I crushed the quest number and one item, sorry.


Regards

**Comment by Dathwada** [comment]
To be honest, you almost got it right.

My added loot and the quest ID are missing now.
I'll correct that.

**Comment by Krovikan** [comment]
I see now the "," and new lines.

**Pull request merged**
