### PR TITLE
Patch 10.2 - Guardians of the Dream

### PR DESCRIPTION
**Pull request by Dathwada**
This will add new content like rares, treasures and more from Patch 10.2 "Guardians of the Dream".

- [ ] [Rares](https://www.wowhead.com/ptr-2/achievement=19316)
    - [x] check coords
    - [ ] add notes
    - [ ] add loot
- [x] [Treasures](https://www.wowhead.com/ptr-2/achievement=19317/)
    - [x] check coords
    - [x] add notes
    - [x] add loot
- [x] ~~Battle Pets~~ (no achievements at the moment)
- [x] [Dragon glyphs](https://www.wowhead.com/ptr-2/achievement=19306)
- [x] Dragonraces
    - [x] Normal
    - [x] Advanced
    - [x] Reverse
    - [x] Challenge
    - [x] Reverse Challenge
- [x] [Profession Treasures](https://www.wowhead.com/ptr-2/items/quality:4?filter=168:99:82;2:11:2;0:0:100200)
- [ ] Achievements
    - [x] [I Dream of Seeds](https://www.wowhead.com/ptr-2/achievement=19013)
    - [x] [Friends In Feathers](https://www.wowhead.com/ptr-2/achievement=19293)
    - [ ] [Emerald Dream Safari](https://www.wowhead.com/ptr-2/achievement=19401)
    - [x] [Fruit of the Bloom](https://www.wowhead.com/ptr-2/achievement=19310)
    - [x] [Kissed by the Wind](https://www.wowhead.com/ptr-2/achievement=19461)

### CODE REVIEW

**Comment by ghost** [comment]
Thank you @pepedressingroom for your contribution! I refactored your code a little bit and introduced some nice QoL features like automatically enabling the correct Athainne node based on current server time. Thank you for all your hard work on laying the foundation for the additional nodes!

**Comment by pepedressingroom** [comment]
Thank you, @wyldclaw 

I have no idea if there is a unified meaning of sunset and sunrise time in game.
If that case, the respawn time of Athainne may not be called sunset and sunrise.
But as to Drustvar or Athainne, the "sunset" is at 19:00, not 15:00 through my observation.

other sunset and sunrise like

- Night Elf's [Touch of Elune](https://www.wowhead.com/spell=154748/touch-of-elune#comments) is 5:30 and 18:30
- Wowpedia [In-game time](https://wowpedia.fandom.com/wiki/In-game_time) is 5:30 and 21:00

**Comment by ghost** [comment]
@pepedressingroom so I need to adjust the time on line 1517 from `15` to `19`?

**Comment by pepedressingroom** [comment]
@wyldclaw , yes, 19:00 is also confirmed by Katalystic on [Wowhead Athainne Comments](https://www.wowhead.com/npc=140044/athainne#comments)

**Pull request merged**
