### PR TITLE
Update zhCN.lua

### PR DESCRIPTION
**Pull request by adavak**

### CODE REVIEW

**Comment by Krovikan** [comment]
Hello: Only I am curious.

Line 226 (Sabriel): Is Theater of the Death instead of Theater of Pain in Simplified Chinese?

**Comment by adavak** [comment]
> 
> 
> Hello: Only I am curious.
> 
> Line 226 (Sabriel): Is Theater of the Death instead of Theater of Pain in Simplified Chinese?

i compare and translated from enUS.

L["sabriel_note"] = "Can appear as one of the champions in the Theater of Pain."

Theater = 剧场
Pain = 伤
Null = 逝

translate one by one should be 伤剧场, added 逝 just nice and official from it.

https://wow.tools/dbc/?dbc=areatable&build=9.0.2.36037&locale=zhCN#page=1&search=TheaterofPain

**Comment by adavak** [comment]
> 
> 
> Hello: Only I am curious.
> 
> Line 226 (Sabriel): Is Theater of the Death instead of Theater of Pain in Simplified Chinese?

btw, 逝 it means not only death but also mean past.

**Comment by Krovikan** [comment]
This tool do a datamine of the data of the game? Is this is, I can use for review some Spanish localizations without play and spoiler myself.

**Comment by adavak** [comment]
> 
> 
> This tool do a datamine of the data of the game? Is this is, I can use for review some Spanish localizations without play and spoiler myself.

yep. officially. and almost time up to date.

**Comment by Krovikan** [comment]
Thanks for all clarifications.

You help me a lot if this shows the strings in the game with Blizzard translation. :)

**Pull request merged**
