### PR TITLE
Patch 10.2 Emerald Dream add Ochre Dreamtalon and Thorn Beasts

### PR DESCRIPTION
**Pull request by pepedressingroom**
- Add Mount: Ochre Dreamtalon
- Add Hunter Pet: Thorn Beasts

### CODE REVIEW

**Comment by ghost** [comment]
@pepedressingroom Looks like you have a few lint issues. Really simple fixes!

Line `1493` need to be updated:
```
    local note = ''
    note = L['thornbeast_note']
```
```
   local note = L['thornbeast_note'] 
```
Similar errors at line `1519` and line `1544`.

**Comment by ghost** [comment]
Also, lint won't catch this but we don't use uppercase in localization keys. So for example `L['Ochre_note_Stage1']` should become `L['ochre_note_stage1']`.

**Comment by ghost** [comment]
I love that you utilized color POIs for the various points of interest for the Ochre Dreamtalon. Let's be sure to indicate those in the note as well. The markup is simple: `{dot:Green}` will render a green circle. You can look at the Forgotten Dragon Treasure in Ohn'ahran Plains for a great example.

**Comment by Krovikan** [comment]
@pepedressingroom In step 4:
```
L['thorn_stag_note'] = '{note:{item:209866s} are different from each kind of beast.}\n\nTo tame 3 kinds of Thorn Beasts (Stag)\n\nSTEP 4\n\nSlain {npc:210976}, then use {item:209866} on the corpse. The stag reborns as {npc:210984} <Thornborn Spirit>.\nCast {spell:1515} on it.\nThree color are available for {npc:210984} with different NPCID. (Black, Brown, Green)'
L['thorn_saber_note'] = '{note:{item:209867s} are different from each kind of beast.}\n\nTo tame 3 kinds of Thorn Beasts (Saber)\n\nSTEP 4\n\nSlain {npc:210975}, then use **{item:209866}** on the corpse. The stag reborns as {npc:210981} <Thornborn Spirit>.\nCast {spell:1515} on it.\nThree color are available for {npc:210981} with different NPCID. (Black, Green, Pale)'
L['thorn_bear_note'] = '{note:{item:209868s} are different from each kind of beast.}\n\nTo tame 3 kinds of Thorn Beasts (Bear)\n\nSTEP 4\n\nSlain {npc:210977}, then use **{item:209866}** on the corpse. The stag reborns as {npc:210988} <Thornborn Spirit>.\nCast {spell:1515} on it.\nThree color are available for {npc:210988} with different NPCID. (Brown, Dark, Green)'
```
you don't change the knife in this lines (in bold).

You have more typos en your commit, but I don't changed (only changed for my file of translation that I commited).

Regards

**Comment by pepedressingroom** [comment]
@wyldclaw, when running format checks, have this error.
```
Checked 236 files, 2 formatting issues found:
  plugins/10_Dragonflight/zones/emerald_dream.lua
  plugins/10_Dragonflight/localization/zhCN.lua

```
what does it mean?

**Comment by Dathwada** [comment]
The code in these files was not formatted as it should be.

**Comment by Krovikan** [comment]
I changed **"different NPCID"** because the player don't need to know that exists different numbers to identify a NPC. Besides is easy that don't understand what is **"NPCID"**

**Comment by pepedressingroom** [comment]
Thank you, @Krovikan , @Dathwada , @wyldclaw .

**Comment by Krovikan** [comment]
I made also in my last commit some other changes as:
 `{npc:149386}\'s Den` to `{location:Ulfar\'s Den}`.
Fixed `The stag reborns as {npc:210981}` as `saber`.
Fixed `The stag reborns as {npc:210988}` as `bear`.
Formatted `5x{item:4537}{dot:Yellow}, 3x{item:209416}{dot:Green}, and 5x{item:208644}{dot:Red}` to `5x {item:4537} {dot:Yellow}, 3x {item:209416} {dot:Green}, and 5x {item:208644} {dot:Red}` with spaces between 5x and { , and between {item:209416} and {dot:Green}. To follow the same format as the rest of the plugin.

Regards

**Pull request merged**
