### PR TITLE
Add data for Apocopocolypse Now

### PR DESCRIPTION
**Pull request by ghost**
I added nodes for all of the Coreless Automa required for the [Apocopocolypse Now] achievement. I did my best to follow the same standards you have in place for other similar datasets such as including research and quest requirements.

I included a note about helpful gear and how to avoid a bug that requires a relog via a comment on Wowhead.

I did what I could for localization as well.

### CODE REVIEW

**Comment by zarillion** [comment]
This looks great @wyldclaw! I didn't have time to look over this more closely this weekend but I will try to approve/merge it soon.

**Comment by mcc1** [comment]
@wyldclaw 
I think all of the locale file for the coreless_automa has a additional "]"

**Comment by ghost** [comment]
Thanks @mcc1 I just pushed a new commit without those pesky square brackets. Good catch!

**Comment by Krovikan** [comment]
Errors in Lint:

Run if [[ ! -f ~/.luarocks/bin/lua-format ]]; then
Cloning into 'LuaFormatter'...
fatal: remote error: 
  The unauthenticated git protocol on port 9418 is no longer supported.
Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.

Error: Failed cloning git repository.
Installing https://luarocks.org/dev/luaformatter-scm-1.rockspec
Error: Process completed with exit code 1.

**Pull request merged**
