### PR TITLE
Add 'Just One More Thing' and more nodes for 'Clued In' 

### PR DESCRIPTION
**Pull request by pepedressingroom**
1. Add more nodes for '_Clued In_'

> - 3 nodes of WQ '_Research: Drakonid of Forbidden Reach_' https://github.com/zarillion/handynotes-plugins/pull/404/commits/00fec9da2ed5c0452a064135cff45192b5fbb338
> - 3 nodes of WQ '_Research: Niffen of Zaralek Cavern_' https://github.com/zarillion/handynotes-plugins/pull/404/commits/07ad6893f9880b861abc1880e9fd78559d95b057
> - 3 nodes of WQ '_Research: Drakonid of Waking Shores_' https://github.com/zarillion/handynotes-plugins/pull/404/commits/7e19f617349e82b009536a71b138a2fb41378f82

2. Add _'Just One More Thing'_ achievement https://github.com/zarillion/handynotes-plugins/pull/404/commits/b358d2bf3af049010d42c3b1b97eb69ce59510e1

> Reference: [Wowhead 'Just One More Thing' comments page](https://www.wowhead.com/achievement=19792#comments)

### CODE REVIEW

**Comment by pepedressingroom** [comment]
Is it the name _**'just_one_more_thing'**_ that causes the formatting issues?

**Comment by Krovikan** [comment]
@zarillion will check the error in Lint from the https://github.com/zarillion/handynotes-plugins/pull/404/commits/edf188f7733be78a894ed38eb71c4522d65f1709 commit.

Regards

**Comment by zarillion** [comment]
Your editor has been changing line endings. These files all had their line endings changed from LF to CRLF:

```
  plugins/10_Dragonflight/common.lua
  plugins/10_Dragonflight/zones/forbidden_reach2.lua
  plugins/10_Dragonflight/zones/ohnahran_plains.lua
  plugins/10_Dragonflight/zones/waking_shores.lua
  plugins/10_Dragonflight/zones/zaralek_cavern.lua
  plugins/10_Dragonflight/localization/deDE.lua
  plugins/10_Dragonflight/localization/enUS.lua
  plugins/10_Dragonflight/localization/esES.lua
  plugins/10_Dragonflight/localization/frFR.lua
  plugins/10_Dragonflight/localization/koKR.lua
  plugins/10_Dragonflight/localization/ruRU.lua
  plugins/10_Dragonflight/localization/zhCN.lua
  plugins/10_Dragonflight/localization/zhTW.lua
```

Make sure the line endings stay as LF so the actual diffs appear in the "Files changed" view.

**Comment by Ioney** [comment]
@pepedressingroom is this ready to merge?

**Comment by pepedressingroom** [comment]
Yes, it's ready to merge. Thanks for your guys help.

**Pull request merged**
