### PR TITLE
Update Rare & Acheivements information for TWW

### PR DESCRIPTION
**Pull request by tfmonk**
Add note for rep quest id and if rare is one time kill.

add paths for some rares to show patrols/routes they take

Add notes to various rares to help explain some information.

Update information for Notable Machines, Biblo Archivist and The Missing Lynx Acheivements

### CODE REVIEW

**Comment by tfmonk** [comment]
@Krovikan Thanks for doing those updates

**Comment by tfmonk** [comment]
Added information for Mereldar Menace achievement in Hallowfall

**Comment by tfmonk** [comment]
Added information for the Smelling History Achievement in Azj-Kahet. 

Still missing some books and need to add some notes to help explain locations and add a poi for the vendor to buy the potion from

**Comment by tfmonk** [comment]
Updated information for the Lost and Found achievement in Hallowfall

**Comment by Krovikan** [comment]
> Updated information for the Lost and Found achievement in Hallowfall

Tell me if you like my fix in Lost and Found.

Regards

**Comment by tfmonk** [comment]
Added information for the Skittershaw Spin achievement in Azj-Kahet

**Pull request merged**
