### PR TITLE
Add Some Drakewatcher Manuscripts Loot

### PR DESCRIPTION
**Pull request by pepedressingroom**
Please help review this request
- Add Drakewatcher Manuscripts Loot for Primal Storms
- Add Drakewatcher Manuscripts Loot for Super Bloom, and [add Loot from Verlann Timbercrush](https://github.com/zarillion/handynotes-plugins/pull/387/commits/545839db655e647f54925b36cc1f9fbf934b4528)
- Add Drakewatcher Manuscripts Loot for Racer's Purses (Is it possible to add it to world quests tooltip?)
  - Dragon Racer's Purse
  - Reach Racer's Purse
  - Cavern Racer's Purse
  - Dream Racer's Purse

By the way, is there any one can tell me how to return a NPC name by its NPC id please?

 #Reference:

- Wind: 12 rares including the 4 wind storm rares
  - Renewed Proto-Drake: Purple Hair
  - Windborne Velocidrake: Swept Horns
- Fire: 19 rares including the 4 fire storm rares
  - Renewed Proto-Drake: Impaler Horns
  - Highland Drake: Toothy Mouth
- Earth: 19 rares including the 4 sand storm rares
  - Windborne Velocidrake: Club Tail
  - Cliffside Wylderdrake: Black Horns
- Water: 21 rares including the 4(6) snow storm rares
  - Highland Drake: Finned Back
  - Cliffside Wylderdrake: Finned Cheek
- Primal: 32 rares including all 16(18) storm rares
  - Windborne Velocidrake: Cluster Horns
  - Renewed Proto-Drake: Heavy Horns

[Budding Dreamtrove](https://www.wowhead.com/item=211413/budding-dreamtrove) (Super Bloom)
  - Renewed Proto-Drake: Green Hair
  - Winding Slitherdrake: Heavy Horns
  - Winding Slitherdrake: Cluster Jaw Horns
  - Winding Slitherdrake: Single Jaw Horn
  - Grotto Netherwing Drake: Chin Spike
  - Grotto Netherwing Drake: Single Horned Crest
  - Grotto Netherwing Drake: Tempestuous Pattern
  - Grotto Netherwing Drake: Finned Jaw

[Dragon Racer's Purse](https://www.wowhead.com/item=199192/dragon-racers-purse)
  - Renewed Proto-Drake: Dual Horned Crest
  - Renewed Proto-Drake: Thin Spined Jaw
  - Windborne Velocidrake: Hooked Snout
  - Windborne Velocidrake: Curled Horns
  - Highland Drake: Curled Back Horns
  - Highland Drake: Hooked Tail
  - Highland Drake: Swept Spiked Head
  - Cliffside Wylderdrake: Large Tail Spikes
  - Cliffside Wylderdrake: Spiked Brow
  - Cliffside Wylderdrake: Curled Head Horns

[Reach Racer's Purse](https://www.wowhead.com/ptr-2/item=204359/reach-racers-purse)
  - Renewed Proto-Drake: Plated Brow
  - Windborne Velocidrake: Small Ears
  - Highland Drake: Swept Horns
  - Cliffside Wylderdrake: Flared Cheek

[Cavern Racer's Purse](https://www.wowhead.com/ptr/item=205226/cavern-racers-purse)
  - Renewed Proto-Drake: Pronged Tail
  - Highland Drake: Tapered Chin
  - Cliffside Wylderdrake: Split Horns
  - Cliffside Wylderdrake: Small Head Spikes
  - Winding Slitherdrake: Small Finned Crest
  - Winding Slitherdrake: Finned Tip Tail
  - Winding Slitherdrake: Pointed Nose
  - Winding Slitherdrake: Triple Jaw Horns

[Dream Racer's Purse](https://www.wowhead.com/item=210549/dream-racers-purse)
  - Winding Slitherdrake: Hairy Jaw
  - Winding Slitherdrake: Short Horns
  - Winding Slitherdrake: Thorn Horns
  - Winding Slitherdrake: Large Finned Tail
  - Grotto Netherwing Drake: Spiked Back
  - Grotto Netherwing Drake: Cluster Spiked Crest
  - Grotto Netherwing Drake: Volatile Pattern
  - Grotto Netherwing Drake: Double Finned Tail

### CODE REVIEW

**Comment by pepedressingroom** [comment]
WORLD_QUEST_REWARD_FILTERS_TITLE is a global string which caused the lint errors.

**Comment by kyletmartinez** [comment]
@pepedressingroom You'll want to use the addon [idTip](https://www.curseforge.com/wow/addons/idtip) for helping with HandyNotes. Provides helpful information in the tooltip such as npc ID!

**Comment by Ioney** [comment]
you have to change it to `_G.WORLD_QUEST_REWARD_FILTERS_TITLE` and `_G.LOOT`. this should fix the lint error.

**Comment by pepedressingroom** [comment]
Thank you @Ioney , But #https://github.com/zarillion/handynotes-plugins/pull/387/commits/9d31cb9853d395af1969813f40aff19c50871fba makes the vignettes of elemental storms do not show rewards correctly.

**Comment by Ioney** [comment]
I think it's because the reward amount is different for each storm type.

@wyldclaw, any idea how to make this work?

**Comment by Ioney** [comment]
im not at home right now so i cant test it ingame, but maybe this helps with displaying the rewards.

**Comment by pepedressingroom** [comment]
> im not at home right now so i cant test it ingame, but maybe this helps with displaying the rewards.

@Ioney Yes, It works now! Thank you.

**Comment by Krovikan** [comment]
@pepedressingroom You have conflicts with master branch. This is because you need add the new commits done in master branch to your brach.

Regards

**Comment by pepedressingroom** [comment]
> @pepedressingroom You have conflicts with master branch. This is because you need add the new commits done in master branch to your brach.
> 
> Regards

@Krovikan I have the recent changes pulled in, and solved the conflicts.
Thank you.

**Comment by pepedressingroom** [comment]
Sorry @Ioney , it seems that the sand storm do not display rewards correctly.
Just some of the storms work well, and the others don't.
So that I moved TRANSMOG_REWARDS afterwards MANUSCRIPT_REWARDS.

**Pull request merged**
