### PR TITLE
Master Some Data Update

### PR DESCRIPTION
**Pull request by pepedressingroom**
Please help review these requests.
- Comment out node Elemental Storm: Dragonbane Keep (removed since 10.1)
- Comment out "Titan Training Matrix I" (now useless)
- Comment out "Whelpling's Shadowflame Crest Fragment", (now trash)
- Add Rare "Biryuk", "Acrosoth", "Overloading Defense Matrix", "Overseer Stonetongue", "Morlash", "Srivantor", "Disoriented Watcher"
- Remove one non-exist node for Rare "Craggravated Elemental"
- Add more Dragonwatcher Manuscripts loot for rares
- Add Dragonwatcher Manuscripts loot for "Fyrakk Assault"
- Modify pois of Elusive Creatures: "Frienzied Amberfir", "Auric Argali", "Crystalscale Stonecleaver"
- Add pois for Rare "Cauldronbearer Blakor"
- Fix quest-id of Rare "Firava the Rekindler"
- Fix quest-ids of "Crystal-Encased Chest"
- Add Achievement "Kissed by the Wind" for node "Ohn'ahra"
- Add a note for "Busted Wyrmhole Generator"

I don't know how to do with the following To-do list.
- Add nodes of Special Working Tables. 
(TO DO: "Shadowflame Crafting Benches" only visible when Fyrakk Assault active;  Add "The Altar of Decay")
- Add comment for extra Vignette of some rares when Dreamsurge is active.
(TO DO: change Vignette when Dreamsurge active)

### CODE REVIEW

**Comment by ghost** [comment]
When it comes to supporting rares with multiple vignette ids (such as Dreamsurge)

I think we should allow the vignette property to be both a single property `vignette = 5109` and a table `vignette = {5109, 5905}` similar to `quest` or `requirements`. If we do that and then update line `1698` in `common.lua` to iterate through and check for any vignette assigned we can support Dreamsurge rares and any other future similar rares.

We would need:
```
self.vignette = ns.AsTable(self.vignette)
```
We would also need:
```
local function IsValidVignette(vignettes, vignetteID)
    for vignette in vignettes do
        if vignette == vignetteID return true end
    end
    return false
end
```
And we would need:
```
if node.vignette and IsValidVignette(node.vignette, self:GetVignetteID()) and
```
Pretty sure all of this would happen inside of `common.lua` for now.

**Comment by ghost** [comment]
Maybe `self.vignette = ns.AsTable(self.vignette)` should be added to `nodes.lua` to help future-proof this concept.

**Comment by ghost** [comment]
Okay @pepedressingroom my code examples up there were missing a lot code BUT I now have the feature included in the `master` branch. I added `vignette = {5115, 5902}` to Char in the Waking Shores and it worked perfectly while the Dreamsurge is active.

**Comment by pepedressingroom** [comment]
Thank you @wyldclaw  for add support for Dreamsurge and review these data.
It's hard for me to understand immediately.
I think I would learn a lot from you guys.

Regards.

**Comment by ghost** [comment]
@pepedressingroom Thank YOU for all of the data!

I was able to get all Fyrakk Assault related notes to show the Requires Fyrakk Assault text in either red or white as well!

Screenshot 2023-11-05 194821
Screenshot 2023-11-05 194839

**Comment by pepedressingroom** [comment]
Thank you @wyldclaw 

And a small issue: 
Tailoring Crafting Table "Azure Loom" do not requires Fyrakk Assault.

**Pull request merged**
