### PR TITLE
Cosmetic update

### PR DESCRIPTION
**Pull request by Dathwada**

### CODE REVIEW

**Comment by ghost** [comment]
Would this be a good branch to fix rare vignette tooltips? Currently we are showing rewards on the rare vignette tooltip even if the Rare group is unchecked in the World Map Button dropdown. I think that feature should honor the checkbox instead. Thoughts?

**Comment by Dathwada** [comment]
> Would this be a good branch to fix rare vignette tooltips?

I don't think it matters in which branch this is fixed. When this branch is merged in a few days.
> Currently we are showing rewards on the rare vignette tooltip even if the Rare group is unchecked in the World Map Button dropdown. I think that feature should honor the checkbox instead.

Yes, I think it's a good idea to implement this.



---
Before we merge this, I want to double check the transmog because I noticed that the wowhead xml sometimes doesn't match the real subclass/slot.

e.g. This two items are boath Cosmetic and Cloaks but the xml subclass is diffenent:
[Item:181810](https://www.wowhead.com/item=181810&xml) subclass: Cosmetic
[Item:188686](https://www.wowhead.com/item=188686&xml) subclass: Cloaks

**Comment by zarillion** [comment]
This looks fine to me. Let me know if you still want to merge this @Dathwada.

**Comment by Dathwada** [comment]
Yes, I would still want to merge this.

**Pull request merged**
