### PR TITLE
Patch 10.2 Update Some Data

### PR DESCRIPTION
**Pull request by pepedressingroom**
Please help review this request
1. update zhCN.lua
2. update common.lua with more Dragonwatcher Manuscripts data.
3. update emerald_dream.lua
- Add currency amount for rare elites and chests. (Need review formatting)
- Add Fruitface's in-cave pois and update locale.
- Add 2 more books. (The Legend of Elun'Ahir, On the Nature of the Dream)
- Add more nodes for Somnut.
- Add more rewards and pois for other rares, fix a typo.
- To remove Slumbering Dream Fragment as reward, which drop all over new map. And add a node for Renewed Dream. 
- Fix some notes of "Druid Glyph List"
- Add two spirit beasts: "Nah'qi" and "Sul'raka"
- Add a node "Super Bloom" to show reward and note

To-Do:
- Add two rare elites "[Raszageth's Last Breath](https://www.wowhead.com/ptr-2/npc=209912/raszageths-last-breath#sounds)", and "[Amalgamation of Dreams](https://www.wowhead.com/ptr-2/npc=209915/amalgamation-of-dreams)"

### CODE REVIEW

**Comment by Dathwada** [comment]
PTR is down right now.
Do you always get +25 rep for killing the rare or is there just a chance to get rep?
`Currency({id = 2652, type = '+25'}), -- Dream Wardens Reputation`

back in korthia we added rep as an `rlabel`.

**Comment by ghost** [comment]
@Dathwada I just recently added reputation rewards to Waking Echo treasures like we did for Korthia as well. `rlabel = ns.status.LightBlue('+200 ' .. L['rep'])` so I agree we should keep it consistent!

Oh I see @pepedressingroom commented out my `rlabel` lines in this commit too

**Comment by pepedressingroom** [comment]
@Dathwada I get Dryad's Supply Pouch (contain +25 rep,  Flightstones, and Dragon Isles Supplies) in bag when the rare elite dying and another +25 rep when looting. Total +50 rep per rare elite.
In recent build, it seems you always get 50 rep per rare elite. Maybe need more killings to confirm this.
(Each rare elite reset  every 4 days with the sub zone, 3 days presence and 1 day absent. Similar with Zeralek Cave rares.)
But [Firebrand Fystia](https://www.wowhead.com/ptr-2/npc=209893/firebrand-fystia) is bugged, dying without quest completed and looting as a normal rare.

@wyldclaw I agree with you. I just offer some data, and not good at coding.

**Comment by pepedressingroom** [comment]
Is there any tool to highlight format issue?

**Comment by Dathwada** [comment]
> Is there any tool to highlight format issue?

Not in Github.
Some or all of us work with visual studio code and this will format the code for us.

**Comment by pepedressingroom** [comment]
> > Is there any tool to highlight format issue?
> 
> Not in Github. Some or all of us work with visual studio code and this will format the code for us.

I am using VScode, but Github format checking made me confused.

**Comment by Dathwada** [comment]
Oh I thought you are editing the code in Github because you edit and commit one file after another.

In default settings vscode should format the code on save.

**Comment by ghost** [comment]
I use Sublime Text still not VScode but I run all my checking via the command line

**Comment by Krovikan** [comment]
Please, @Dathwada @wyldclaw @Ioney , check my change to enUS. I think that is better as I rewrite. Check also my English expressions.

Regards

**Comment by Krovikan** [comment]
@pepedressingroom You need to do the action that says Github to avoid errors:

> Add more commits by pushing to the [Patch-10.2](https://github.com/pepedressingroom/handynotes-plugins/tree/Patch-10.2) branch on [pepedressingroom/handynotes-plugins](https://github.com/pepedressingroom/handynotes-plugins).

**Comment by pepedressingroom** [comment]
> @pepedressingroom You need to do the action that says Github to avoid errors:
> 
> > Add more commits by pushing to the [Patch-10.2](https://github.com/pepedressingroom/handynotes-plugins/tree/Patch-10.2) branch on [pepedressingroom/handynotes-plugins](https://github.com/pepedressingroom/handynotes-plugins).

Thank you @Krovikan I am new to coding and Github, and need some time to learn.

By the way, you may have missed that L['fruitface_note'] has updated.

Regards.

**Pull request merged**
