### PR TITLE
Mists of pandaria

### PR DESCRIPTION
**Pull request by Ioney**
Rares added
Treasures added
Lorewalker Achievement locations added
Critter locations for Squirrel Achievement added
'When in Ihgaluk, Do as the Skumblade Do' Achievement nodes added

### CODE REVIEW

**Comment by Krovikan** [comment]
Hello @Ioney 

I think that these lines needs a change:

L['options_icons_lorewalker'] = 'Lorewalker'
L['options_icons_lorewalker_desc'] = 'Shows the locations for the Lorewalker achievement.'

The achievement is not "Lorewalker". The name is "Loremaster of Pandaria".

I did these changes in my file (applicable to enUS but I don't did it while I wait your answer):

L['options_icons_lorewalker'] = {achievement:6541}
L['options_icons_lorewalker_desc'] = 'Shows the locations for the {achievement:6541} achievement.'


Regards

**Comment by Ioney** [comment]
I guess my wording could be changed to make it more clear.

The lorewalker achievement(s) consist of multiple achievements where you find staues/monuments in pandaria. Ultimately you will get exalted with the "lorewalkers" factions.

Here is is a guide:
www.wowhead.com/guides/reputation/guide-to-the-lorewalkers

**Comment by Krovikan** [comment]
> I guess my wording could be changed to make it more clear.
> 
> The lorewalker achievement(s) consist of multiple achievements where you find staues/monuments in pandaria. Ultimately you will get exalted with the "lorewalkers" factions.

Thanks. I only change the number of achievements and If you want the text of enUS can remain as this:

L['options_icons_lorewalker'] = {achievement:**6548**}
L['options_icons_lorewalker_desc'] = 'Shows the locations for the {achievement:**6548**} achievement.'


Regards

**Comment by zarillion** [comment]
This PR has commits already merged to `master`. It includes WotLK commits that should not be part of this PR.

In your repo:

```
git checkout MistsOfPandaria
git remote add upstream git@github.com:zarillion/handynotes-plugins.git
git fetch upstream
git rebase upstream/master
git push --force
```

**Pull request merged**
