### PR TITLE
Rep Reward

### PR DESCRIPTION
**Pull request by Ioney**
Still needs more testing.

### CODE REVIEW

**Comment by Ioney** [comment]
i'm not too happy with "completed" maybe "warband gained" sounds better?
what about "incomplete"? "warband incomplete"?

suggestions are welcome

**Comment by Krovikan** [comment]
Maybe  this:
imagen
But with (Rep gained) or (Rep incomplete) instead (Rep)?

**Comment by tfmonk** [comment]
How about "Claimed by Warband" in green and "Not Claimed by Warband" in red/blue?

**Comment by tfmonk** [comment]
Or you could add a header above the rep?

So it would be something like

"One time Warband reputation bonus (Claimed)" or "One time Warband reputation bonus (Not Claimed)"
+85 The Weaver
+85 The General
+85 The Vizier

**Comment by Dathwada** [comment]
How about hiding the reward if it has already been claimed?

**Comment by Krovikan** [comment]
> How about hiding the reward if it has already been claimed?

Maybe is the best. The screenshot above with the (Rep) and if is only 1 earnable, hide when claimed.

And when the Rep is at their maximum status, hide all these sources.

**Comment by tfmonk** [comment]
Wouldn't you want this to kind if function in the same way other rewards display, so there is a consistent behaviour with them? So hiding the rep might not be the best way.

How would that work if I wanted to look at a rare I've already killed to see if it gave rep?

Hiding the rep rewards if your at max status with the faction isn't a great idea as it makes it harder to do the ones that give rep should you be looking to push for a paragon chest.

**Comment by Krovikan** [comment]
Sorry, I didn't think about Paragon chests. 😅

**Comment by Dathwada** [comment]
> Hiding the rep rewards if your at max status with the faction isn't a great idea

I never said that. I only meant that the reputation reward should be hidden if it has already been claimed by one character on the account. It would be unnecessary information for all other characters on that account.

We could also do both things and add a setting and let the user decide.
1. Show (complete) or (incomplete)
2. Hide the reputation reward if completed on the account

**Comment by tfmonk** [comment]
@Dathwada that bit was in response to @Krovikan comment

I like the idea of the 2 option to either show the completed or hide it if already claimed, as either way some users may not like the approach so this way they get a choice, as long as it's not too complex to create those options

**Comment by Dathwada** [comment]
Oops, I overlooked that, I'm very sorry.

**Comment by tfmonk** [comment]
thought a bit more and how about just keeping it simple with a Claimed/Not Claimed status for the rep?

**Pull request closed without merging**
