### PR TITLE
zhCN update.

### PR DESCRIPTION
**Pull request by adavak**
shadowlands next.

### CODE REVIEW

**Comment by zarillion** [comment]
Thanks for the hard work on this! I cannot speak Chinese but the few translations I put into Google translate seemed to work well.

For the existing translations you changed, were the old ones not well translated?

**Comment by adavak** [comment]
The shadowlands will translate very soon.

This commit fixed all the previous components were completely completed in English. The used are too old and there are too many missing strings, and the committed have been perfected.

**Comment by zarillion** [comment]
When you get a chance please update your `master` branch to resolve the conflicts and I'll get this merged in. We could also wait until you have the Shadowlands translations ready and merge then.

**Comment by adavak** [comment]
> 
> 
> When you get a chance please update your `master` branch to resolve the conflicts and I'll get this merged in. We could also wait until you have the Shadowlands translations ready and merge then.

update zhCN Ardenweald parts.

because some zone name and mob or achievement will dump the game data. another time will contiune the others.

**Comment by adavak** [comment]
all done and wait for next main update.

**Comment by adavak** [comment]
btw

could relase old mod (WarlordsOfDraenor \ MechagonAndNazjatar \ VisionsOfNZoth) addons. the zhCN all brand new.

**Comment by zarillion** [comment]
Merged in https://github.com/zarillion/handynotes-plugins/commit/8fe02aa75ed329e86312e7cd25ed2c7bfd927621.

**Pull request closed without merging**
