### PR TITLE
Cup update

### PR DESCRIPTION
**Pull request by Dathwada**
This will add the IsCalendarEventActive function we talked about. Thanks to @wyldclaw for this function.

I had to create two new groups for the Kalimdor Cup and Eastern Kindoms Cup.
I also removed a duplicated DRAGONRACE group.

I added IsCalendarEventActive to Secrets of Azeroth as well, but I'm not quite sure if you still could do the Quests / Buried Satchels without the event being active.

Feel free to improve/change things.

### CODE REVIEW

**Comment by Ioney** [comment]
secrets of azeroth is still available after the event.

only https://www.wowhead.com/achievement=18642 and the FoS https://www.wowhead.com/achievement=19080 are now not doable anymore

**Comment by Dairyman** [comment]
`C_Calendar.SetMonth(0)` does nothing. The value needs be non zero to have any effect, what it does is move the month by given offset.

That means if you open the Calendar and go to an other month other then the current and close it, the `IsCalendarEventActive()` function checks for the wrong month.

For changing the month use 
```Lua
local current = C_DateAndTime.GetCurrentCalendarTime()
C_Calendar.SetAbsMonth(current.month, current.year)
```
Calling this or `C_Calendar.SetMonth(<offset>)`does change the Calendar UI.

As the current implementation does only check if the event is active today you could cache the events e.g:
```Lua
local activeCalenderEvents = {}

local function updateActiveEvents()
    -- calling C_Calendar.SetAbsMonth does change the UI
    if CalendarFrame and CalendarFrame:IsShown() then
        C_Timer.After(5, updateActiveEvents)
        return
    end

    -- set Calendar to current month
    local current = C_DateAndTime.GetCurrentCalendarTime()
    C_Calendar.SetAbsMonth(current.month, current.year)

    wipe(activeCalenderEvents)
    local day = current.monthDay
    for i = 1, C_Calendar.GetNumDayEvents(0, day) do
        local event = C_Calendar.GetDayEvent(0, day, i)
        activeCalenderEvents[event.eventID] = true
    end

    -- hours until midnight + minutes unit midnight + 5 extra seconds
    local nexDay = (((23 - current.hour) * 60) + (60 - current.minute)) * 60 + 5
    -- this will call updateActiveEvents between 00:00:05 to 00:01:04
    C_Timer.After(nextDay, updateActiveEvents)
end
updateActiveEvents()

local function IsCalendarEventActive(eventID)
    return activeCalenderEvents[eventID] and true or false
end
```

**Comment by Dathwada** [comment]
Thank you for sharing this with us and providing a code example of how we could improve this function.

I tested our function further and you are absolutely right. The wrong Month will be checked if the player switches to another month and closes the calendar.

I tested your code ingame (after renaming nexDay to nextDay) and one "problem" I encounterd is that if the player uses the calendar and goes to another month, this function will reset the month every 5 seconds (or how much time is left on the timer) to the current month.

I would say we remove:
```lua
  -- calling C_Calendar.SetAbsMonth does change the UI
  if CalendarFrame and CalendarFrame:IsShown() then
      C_Timer.After(5, updateActiveEvents)
  end
```
And it should work as well.

**Comment by Dairyman** [comment]
Oh, missed a return there,
```Lua
  -- calling C_Calendar.SetAbsMonth does change the UI
  if CalendarFrame and CalendarFrame:IsShown() then
      C_Timer.After(5, updateActiveEvents)
      return
  end
```
so that it does nothing until calendar is closed...

**Comment by Dathwada** [comment]
I have to correct myself.
Earlier, I tested it with [WowLua](https://www.curseforge.com/wow/addons/wowlua) ingame and run the code, when the calendar was open, only **then** the month was reset every 5 seconds.

The condition `if CalendarFrame and CalendarFrame:IsShown() then` will only be true if you just login, the function will be called and somehow the calender is open (I guess this will never happen) or the timer for the nextDay will trigger, the function will be called and you have the calendar open.

**Review by zarillion — APPROVED** [review]

**Pull request merged**
