### PR TITLE
Legion

### PR DESCRIPTION
**Pull request by ghost**
Add nodes for all Argus rare spawns for [Commander of Argus] and all Argus treasure spawns for [Shoot First, Loot Later]

### CODE REVIEW

**Comment by Krovikan** [comment]
I think that was needed in the locales files the lines:

local Gold = ns.color.Gold
local Orange = ns.color.Orange
local Red = ns.color.Red

for have this colors in the lines with them.

I have a failure in Lint and I don't know if is for add this local colors in my file (esES.lua).


Regards

**Comment by ghost** [comment]
Sorry for that terrible typing on the commit message. It should read "Add notes for [Bringing Home the Beacon]"

**Comment by Krovikan** [comment]
I guess that local colors is needed to add when you write the first line that uses a color?

I say that because I saw that you left Gold and Orange in my file and cleared the Red.

This means that the other translators need to do the same thing? Only add the local colors when they have 1 line at least with local used?

For last. Is not better do these local colors (Red, Orange and Gold) as a global local colors for the plugin and don't have the necessity of add in locales files of translation?

The last question above is from the unknowledge of LUA.


Regards

**Comment by ghost** [comment]
That is a good question @Krovikan and I don't know what way is better. I'm sure @zarillion has some thoughts on the best way to do it!

**Comment by zarillion** [comment]
When possible, colors should be applied in the zone/code files instead of the locale files so they do not have to be repeated for each supported locale. Sometimes it does make sense to put the color in the locale file if the locale string is very long and only some parts of it are colorized. If the entire string is colorized and that string is then used directly in the code, move the color to the code.

Putting the `local` assignment at the top of a file is always optional. Assigning something to a local variable is helpful when you use it many times and do not want to reference the full object path every time. For instance, these are both valid:

```lua
L['text1']  = ns.color.Red('This is some red text')
L['text2']  = ns.color.Red('This is more red text')
L['text3']  = ns.color.Red('This is also red text')
```

```lua
local Red = ns.color.Red

L['text1']  = Red('This is some red text')
L['text2']  = Red('This is more red text')
L['text3']  = Red('This is also red text')
```

If the color is used only once in the entire file, you can either use it directly or assign it to a `local`. If the color is used multiple times, I prefer you assign it to a local instead of repeating `ns.color.` every time.

**Comment by Ioney** [comment]
```lua
local Color = ns.color

L['text1']  = Color.Red('This is some red text')
L['text2']  = Color.Gold('This is gold text')
```
would be another option

**Comment by Krovikan** [comment]
These:

L['book_1'] = 'Book 1 (Sunday)'
L['book_2'] = 'Book 2 (Monday)'
L['book_3'] = 'Book 3 (Tuesday)'
L['book_4'] = 'Book 4 (Wednesday)'
L['book_5'] = 'Book 5 (Thursday)'
L['book_6'] = 'Book 6 (Friday)'
L['book_7'] = 'Book 7 (Saturday)'

Is for all countries?

In Spain the week starts in Monday, not Sunday.


Regards

**Comment by ghost** [comment]
@Krovikan according to Wowhead yes, those are from someone who plays EU. I confirmed yesterday when I got book 3 (Tuesdsay).

**Comment by ghost** [comment]
@Dathwada if Orix is listed as Collectible will he ever disappear? He offers a toy, a pet, but I also have the item listed that is used to teleport to Rezira the Seer. I thought Collectible only disappeared when all rewards were known. But that item won't stay in a users bag forever, will it? Maybe putting that item in his note is better than a reward...

**Comment by Dathwada** [comment]
> @Dathwada if Orix is listed as Collectible will he ever disappear? He offers a toy, a pet, but I also have the item listed that is used to teleport to Rezira the Seer. I thought Collectible only disappeared when all rewards were known. But that item won't stay in a users bag forever, will it? Maybe putting that item in his note is better than a reward...

Yes he will disappear.
I collected the pet and toy and he disappeared on my map.

**Pull request merged**
