### PR TITLE
Using C_TooltipInfo instead of custom created tooltips

### PR DESCRIPTION
**Pull request by Voopie**
On the ruRU client npcs names are always shown as UNKNOWN
With these changes, the names are shown properly

### CODE REVIEW

**Comment by Voopie** [comment]
I don't know what to say about 'Failed' :( Maybe I'm just blind

**Comment by ghost** [comment]
@Voopie The lint check and formatting is very specific and aggressive. There is documentation in the repo that shows how to implement luacheck if you're interested or someone may have to pull your branch and run the formatter on it.

**Comment by Ioney** [comment]
change
```lua
local NameResolver = {
    cache = {},
    prepared = {}
}
```
to
```lua
local NameResolver = {cache = {}, prepared = {}}
```
in core/util.lua

this should fix the lint error

**Comment by Voopie** [comment]
> formatting is very specific and aggressive

@wyldclaw Yep, I noticed :)
@loney Thank you! Let's check it out

**Comment by zarillion** [comment]
Thanks for the contribution @Voopie! The changes also work in-game for me so I'm going to merge this and send it out today. Its good to finally have an alternative way of doing this.

**Pull request merged**
