### PR TITLE
Some fixes and additions

### PR DESCRIPTION
**Pull request by pepedressingroom**
Fixes
- Fix Azure Loom, remove FyrakkAssault requirement
- Fix the note of Quackers the Terrible and Fix Bloodgulllet node as NPC
- Fix vignette multi-displayed rewards of Amalgamation and Raszageth(https://github.com/zarillion/handynotes-plugins/pull/389/commits/b08eab6780f86f7604f4b4a2f7106a26fd781635)
- Update zhCN 'silent_mark_note' and 'azure_somnowl_note' due to https://github.com/zarillion/handynotes-plugins/commit/f31bd983e5209bf27698e222e61b35a692e9d996
- [Fix the note of TOY: Tiny Box of Tiny Rocks and and update zhCN and zhTW translation](https://github.com/zarillion/handynotes-plugins/pull/389/commits/a5041e503a6e7fd2cbfc22ef91d4aa4c1252587c)
- [Fix the coord of Broodweaver Araznae](https://github.com/zarillion/handynotes-plugins/pull/389/commits/cc83966f6b6d7934a27c93a03d548cd43986e755)
- [Athainne only visable for hunters now](https://github.com/zarillion/handynotes-plugins/pull/389/commits/e4f4cc3d6db2502dca655e635d6ae207ca72d314)
- [Fix criteria of Blazing Shadowflame Chest](https://github.com/zarillion/handynotes-plugins/pull/389/commits/4c1b5012d02129c09f1ce920069e722387154e6f)
- [Fix Amirdrassil treasure quest ids](https://github.com/zarillion/handynotes-plugins/pull/389/commits/86a4894a740f53d098c811832bfc95d32919902d)
- [ns.reward.Apprearance add display option: 'show_transmog_rewards'](https://github.com/zarillion/handynotes-plugins/pull/389/commits/7d8249772a10f8a3b696a489ceaa3ff65f18f65a)

Additions
- [Add The Altar of Decay in Brackenhide Hollow](https://github.com/zarillion/handynotes-plugins/pull/389/commits/28df4608a20b7b8ea67115c90179b0459123f0e3)
- [Add World Boss Aurostor rewards](https://github.com/zarillion/handynotes-plugins/pull/389/commits/6b265173801b0451a476fb8aa9ff32c3d6289c97) (Is it possible to add extra tooltips such as rewards or achievements to world quests just like rare vignette?)
- [Add the vignette and some node for Dreamsurge](https://github.com/zarillion/handynotes-plugins/pull/389/commits/66d9d68adf0267a01c0e741cf9450fef0eb2f7a2)
- [Add the currency count display for Revival Catalyst](https://github.com/zarillion/handynotes-plugins/pull/389/commits/d164fb9a3a336ec9e0ab18ed3184b84e0402ebd2)
- [Display count for Dragon Shard and KPs to max out the Profession Trees.](https://github.com/zarillion/handynotes-plugins/pull/389/commits/4cd2d1bc43615440cf09448cbc51024bdf70b33a)

### CODE REVIEW

**Comment by Ioney** [comment]
just paste the link to the commit like so : `https://github.com/zarillion/handynotes-plugins/pull/389/commits/f1b76a3e1fb83d350e1c5a846f16b0f5e79488fb`
https://github.com/zarillion/handynotes-plugins/pull/389/commits/f1b76a3e1fb83d350e1c5a846f16b0f5e79488fb

**Comment by pepedressingroom** [comment]
> just paste the link to the commit like so : `https://github.com/zarillion/handynotes-plugins/pull/389/commits/f1b76a3e1fb83d350e1c5a846f16b0f5e79488fb` [f1b76a3](https://github.com/zarillion/handynotes-plugins/commit/f1b76a3e1fb83d350e1c5a846f16b0f5e79488fb)

Thank you @Ioney

**Comment by Krovikan** [comment]
@pepedressingroom You have a mistake in all locales and in Azure_span.lua

`L["altar_of_decay_label"]` must be `L['altar_of_decay_label']`.

Regards

**Comment by pepedressingroom** [comment]
> `L["altar_of_decay_label"]` must be `L['altar_of_decay_label']`

Thank you @Krovikan

**Comment by Krovikan** [comment]
@pepedressingroom L['khadin_prof_note'] = 'Gana %d more {currency:%d}s to max out {spell:%d} profession tree.'

You can show me a sentence did it with %d replaced? Can be of any profession, only for translate accurate.

Regards

**Comment by pepedressingroom** [comment]
> @pepedressingroom L['khadin_prof_note'] = 'Gana %d more {currency:%d}s to max out {spell:%d} profession tree.'
> 
> You can show me a sentence did it with %d replaced? Can be of any profession, only for translate accurate.
> 
> Regards

屏幕截图 2023-12-02 001910

@Krovikan I list how many currencies to max out tree nodes of the 2 professions for a player to decide either one to exchange Dragon Shards.
My English is not good, and do you think the sentences make sense?

Regards.

**Comment by zarillion** [comment]
Looks like some globals need to be added to `.luacheckrc` still for the build to pass. I'm going to wait on merging these for now.

**Comment by Ioney** [comment]
@pepedressingroom
Is there anything else you want to add to this PR?

> * [Add World Boss Aurostor rewards](https://github.com/zarillion/handynotes-plugins/pull/389/commits/6b265173801b0451a476fb8aa9ff32c3d6289c97) (Is it possible to add extra tooltips such as rewards or achievements to world quests just like rare vignette?)

should be possible, i think we just need the quest id and add another hook function

**Comment by pepedressingroom** [comment]
@loney

I've been AFK for round half a year, since the returning news of the china server.
Due to my lacking of experience, this PR looks like a great mess.
Maybe I should not add too many things in one PR, and please help look after this PR.

I still have some thought and data to add in Dragonflight, but it will take me some time to sort.

**Comment by Ioney** [comment]
@pepedressingroom you did a lot of commits since your last comment, are you still working on something or can i merge this PR?

**Comment by pepedressingroom** [comment]
@Ioney This PR seems ready to be merged now. Thank you for your guys help.

**Pull request merged**
