### PR TITLE
Fix vignette tooltip frame sizing

### LINKED ISSUE #92: Chest tooltips not displaying correctly since fix
The tooltip's for chest mouseovers are not being displayed correctly.
It's missing the black backdrop.

https://i.imgur.com/RucHnly.png

### PR DESCRIPTION
**Pull request by Wevah**
Fixes #92.

(Adapted from https://github.com/zarillion/handynotes-plugins/issues/89#issuecomment-799398409.)

### CODE REVIEW

**Comment by Krovikan** [comment]
Thanks @Wevah. The Autor @zarillion checks ASAP.

**Comment by zarillion** [comment]
This is close, but we still have one remaining issue. If any other addon performs this same trick, we will end up rendering the rewards multiple times as the other addons call `Show()`. For instance, I use the same trick this addon uses in my personal forked copy of the idTip addon to show Vignette IDs on the tooltips (so I know what ID to put in this addon). When the two run together, this is the result:

image

The background is fixed, which is awesome! But we need to also figure out if we've already added rewards to this particular tooltip if Show is called again. My current thinking is we look for `Hide()` and if it has not been called since our last `Show` hook, do nothing, unless you have a better idea.

**Comment by zarillion** [comment]
For reference, here is a patch for idTip to show Vignette ids using this same method:

```diff
--- idTip.lua.orig      2021-03-17 20:27:55.587993000 -0500
+++ idTip.lua   2021-03-17 20:20:45.888765100 -0500
@@ -24,6 +24,7 @@
   visual = "VisualID",
   source = "SourceID",
   species = "SpeciesID",
+  vignette = "VignetteID",
 }

 local isClassicWow = select(4,GetBuildInfo()) < 20000
@@ -379,4 +380,18 @@
   hooksecurefunc("TaskPOI_OnEnter", function(self)
     if self and self.questID then addLine(GameTooltip, self.questID, kinds.quest) end
   end)
+
+  -- Vignettes
+  local isOwnShowCall = false
+  hooksecurefunc(GameTooltip, 'Show', function(self)
+    if isOwnShowCall then return end
+    local owner = self:GetOwner()
+    if owner and owner.vignetteID then
+      addLine(self, owner.vignetteID, kinds.vignette)
+      isOwnShowCall = true
+      self:Show()
+      isOwnShowCall = false
+    end
+  end)
+
 end
```

Whatever solution we come up with I'll want to mirror here so that the vignette id isn't added multiple times!

**Comment by Wevah** [comment]
Hm, good call. Maybe store the vignette ID and use that to check, without zeroing it out after the `Show()` call?

Edit: Of course, that could break if the user mouses over the same vignette twice in a row. Unsetting in `Hide()` is probably the better solution. I'll try some stuff after I get some rest, if nobody else gets to it first.

**Comment by Wevah** [comment]
I *think* I found a hacky workaround, but it needs more testing.

Actually, depending on the defined order of calls, it might not be as hacky as I thought.

**Comment by Wevah** [comment]
The latest changes should prevent duplications, however there's a bit of a jiggle of sorts often when the vignette is moused over. It seems like a chain of `Show()`s is called twice; there may be a better place to hook the reset (`Hide()` didn't seem to work well).

Edit: That said, I think it's probably okay for live until a better hook is found.

**Comment by zarillion** [comment]
When I try this change (and apply the matching change to idTip), the rewards show up for a split second and then disappear. Vignette tooltips are constantly refreshed by Blizzard, and `IsShown()` is not called between each refresh. The tooltip does, however, call `ClearLines()` each time it refreshes, so changing `IsShown => ClearLines` fixes it for me.

I'm not convinced calling `Show()` in the handler is necessary. When I comment it out in both this addon and idTip, the tooltip still renders with the proper background. Either Blizzard changed something or something else about this change makes the tooltip work fine without calling `Show()` again. I'm going to remove the `Show()` call after the merge and continue to keep an eye on it. If I see it render improperly again I'll add it back in.

Thanks for the work on this. I'm going to merge it in and make the changes I mentioned above.

**Pull request merged**
