### PR TITLE
Add to zaralek cavern rares loot table

### PR DESCRIPTION
**Pull request by Zeeda17**
Added transmog and remove items not showing on wowhead loot table. Adde…d drake customization or a comment if item was not in common.lua.

Feel free to adjust code as you wish. Just trying to take some of the grunt work off your hands.

### CODE REVIEW

**Comment by Ioney** [comment]
@zarillion looks like most or at least some of them are zone drops with <1% drop chance. should we merge it anyway?

**Comment by zarillion** [comment]
Thanks for the submission @Zeeda17! @Ioney lets not merge it as-is, but we can look at the entries here and decide how we want to approach this.

<1% zone drops are always a nuiscance. We do not want to bloat the rare tooltips with copy-paste drops that are largely the same for every mob in the zone. Traditionally this plugin has been created/updated to answer two core questions:

1. Where are the points of interest in the map?
2. What *unique* rewards can I get from those points of interest?

Because these rewards are not really unique to any single point of interest, where should they be displayed? I could see them as being considered outside the scope of this addon. I could also see us added a "Zone Drops" node in a corner of the map that displays all of these drops with a description about how they drop.

For now, lets go through these and reduce them down to just the transmog rewards that *only* drop from that mob. For instance, the `Goopal's Visage` transmog item clearly only drops from Goopal, so we should include it in his tooltip.

**Comment by Ioney** [comment]
i sometimes add transmogs if they drop form one rare more often than from others

for example: wowhead droprate on two rares is >10% and all others have <2%. i would add it to the two rares.

**Comment by Zeeda17** [comment]
I didn't even look at the drop rates. Very valid to remove super low chance drop rates to avoid triggering people's completionism. Thank you for the addon and all your work on it.

**Pull request merged**
