### PR TITLE
add 2 achievements "Clued In" and "Goggle Wobble"

### PR DESCRIPTION
**Pull request by pepedressingroom**
Hi guys, I use `C_TaskQuest.IsActive(quest)` to add a new requirement `InProgress`, which can be used for achievements and loots that need certain world quest, daily quest, or other quest active.
Do you think it necessary to add this requirement? 
`InProgress` sounds strange, could it be merged into `ns.requirement.Quest`.

I added it in "Clued In",  but did not add it for "Goggle Wobble".
Because "Goggle Wobble" can be completed during world quest _e.g_ `{78931}` or intro quest chain _e.g_ `{77483, 76448, 76557, 77415,}`.
It will be like this `ns.requirement.InProgress(77483, 76448, 76557, 77415, 78931)`
I know it's just a simple achievement, and I make it complicated.

### CODE REVIEW

**Comment by ghost** [comment]
@pepedressingroom We don't use World Quest IDs for stuff like this or localization. If the quest isn't available then it will cause issues in the display. @Dathwada can probably explain a little better! We talked about it a while back in the Discord server.

**Comment by pepedressingroom** [comment]
@wyldclaw , 
Get it. I have removed this requirement.

**Comment by pepedressingroom** [comment]
Add 3 nodes of WQ 'Research: Drakonid of Forbidden Reach' for 'Clued In'


_forbidden_reach2.lua_
> ```
> map.nodes[19621537] = ns.node.CluedIn({
>     label = L['decaying_fishing_bucket'],
>     quest = 77362,
>     location = L['decaying_fishing_bucket_note']
> })
> 
> map.nodes[18241313] = ns.node.CluedIn({
>     label = L['forgotten_fishing_pole'],
>     quest = 77362,
>     location = L['forgotten_fishing_pole_note']
> })
> 
> map.nodes[10591156] = ns.node.CluedIn({
>     label = L['overgrown_fishing_bench'],
>     quest = 77362,
>     location = L['overgrown_fishing_bench_note']
> })
> ```

_enUS.lua_
> ```
> L['decaying_fishing_bucket'] = 'Decaying Fishing Bucket'
> L['decaying_fishing_bucket_note'] = 'On the top floor of the tower.'
> L['forgotten_fishing_pole'] = 'Forgotten Fishing Pole'
> L['forgotten_fishing_pole_note'] = 'On the ground level.'
> L['overgrown_fishing_bench'] = 'Overgrown Fishing Bench'
> L['overgrown_fishing_bench_note'] = 'An overgrown rock, hard to see.'
> ```


_zhCN.lua_
> ```
> L['decaying_fishing_bucket'] = '腐烂鱼桶'
> L['decaying_fishing_bucket_note'] = '在塔的最顶层'
> L['forgotten_fishing_pole'] = '被遗忘的鱼竿'
> L['forgotten_fishing_pole_note'] = '在最底层'
> L['overgrown_fishing_bench'] = '长满杂草的钓鱼椅'
> L['overgrown_fishing_bench_note'] = '覆满青苔的岩石，不大显眼'
> ```

**Comment by Krovikan** [comment]
The following is only my opinion:

Instead of comment in closed PR you can open one new PR with "3 nodes of WQ 'Research: Drakonid of Forbidden Reach' for 'Clued In' forgotten" comment (for example) and commit  the changes.

The same with other comments in closed PRs.

Regards

**Comment by Dathwada** [comment]
> @pepedressingroom We don't use World Quest IDs for stuff like this or localization. If the quest isn't available then it will cause issues in the display. @Dathwada can probably explain a little better! We talked about it a while back in the Discord server.

Like @wyldclaw already explained.
Sometimes when the world quest is not active, the API does not return the quest name. That's why we don't use the quest ID for world quests.

**Pull request merged**
