### PR TITLE
[i18n] Korean localization

### PR DESCRIPTION
**Pull request by soaa**
This is the first draft of Korean translation. 

Only the essential parts are translated and I'm working on it.

### CODE REVIEW

**Comment by Krovikan** [comment]
I added the fault lines. Now the Lint process pass your PR good.

Please, don't eat lines or Lint fail.

Fell free to join to our Discord to talk in the channel translators and Author tell you more (when he wake up, is in USA).

https://discord.gg/ssZaynGy

**Comment by soaa** [comment]
@Krovikan 

Thanks. 
There was no contributing guide document in project, so I thought that just localizing strings is enough.

So you're saying is all test checks must be passed by running build.sh prior to make a pull request.
Is it right?

**Comment by Krovikan** [comment]
Hello.

I am not coding also. I only translate the addon to my locale (esES).

The lint process, the 1st time, is only do it by a developer or collaborator.

I saw errors and I was correcting them with my commits (only was errors for eat some lines (helmix, provis, serenade, etc).

The last commit of string was a error from me. I eat me a **'** when I copy the last lines. :P

You can encounter more info and answers at our Discord. We are 7 translators and 2 developers. There you can ask and say anything you need.

See you there

**Comment by Krovikan** [comment]
Line 706 is now on your locale file:

L['architects_reserve_note'] = 'Complete the {quest:64829} questline from {npc:180630} in Pilgrim\'s Grace to unlock the treasure.'

The change is that now is very short the note. Because don't need to wait 1 day to unlock the treasure.

**Comment by zarillion** [comment]
This is awesome, thank you for the hard work! I will work on a `contributing.md` file for future contributors that hopefully will make this process easier.

You mention you are still working on it, so I will leave this PR open for now. Let me know when you would like to merge what you have so far.

**Comment by soaa** [comment]
@zarillion
Thanks.
As you know there's too much text to translate, so I mean I'm working on it little by little. :)

I don't have much time on my weekdays, I'll make additional PR this weekends with at least core/koKR.lua completed.

**Comment by zarillion** [comment]
That sounds like a good plan. I will merge this PR in and we can get more of your translations in future PRs.

**Comment by Krovikan** [comment]
Don't worry for the error with my commit. Is normal.

**Comment by zarillion** [comment]
Your initial translations have been merged in and will be released later today. If you would like to contribute translations more easily in the future, you can join our discord server and I can grant you contributor access to the repository directly. You can also keep submitting PRs if you want.

**Pull request merged**
