### PR TITLE
Add Profession items for TWW Zones

### PR DESCRIPTION
**Pull request by tfmonk**
Add Profession items for TWW Zones

Jewelcrafting
Alchemy
Enchanting
Engineering
Herbalism
Leatherworking
Tailoring
Mining
Skinning
Inscription
Blacksmithing

### CODE REVIEW

**Comment by Dathwada** [comment]
I'll fix the formatting for you.

**Comment by tfmonk** [comment]
thanks @Dathwada not 100% sure where im going wrong as i mirrored everything the best i can

**Comment by tfmonk** [comment]
why does formatting pass this was when say the Alchemy Earthen Iron Powder for Isle of dorn is one line and say the jewlcrafting Earthen Gem Pliers are over a couple of lines?

**Comment by Dathwada** [comment]
The [formatter](https://marketplace.visualstudio.com/items?itemName=Koihik.vscode-lua-format) we use is configured to allow 80 characters per line (comments do not count). Some rules don't apply to the localization files. The formatter has many rules for formatting the code, I wouldn't try to do this manually.

`dor.nodes[32456032] = PT.Alchemy({quest = 83840, id = 226265, parent = map.id}) -- Earthen Iron Powder`
(102 chars, but only 79 chars without the comment)

`dor.nodes[34845219] = PT.Jewelcrafting({quest = 83891, id = 226317, parent = map.id}) -- Earthen Gem Pliers`
(107 chars, but 85 without the comment)

**Comment by tfmonk** [comment]
that makes sense, thanks for that information. If i do further updates i will leave the formatting if theres issues

**Comment by tfmonk** [comment]
I've gone through all the main profession items and added the information and reviewed all the ones that were there before, look like they are all done now

**Comment by pepedressingroom** [comment]
misspell:
`aquest = 83909`

**Comment by tfmonk** [comment]
thanks @pepedressingroom its fixed now

**Comment by tfmonk** [comment]
Just updated a handful of rares tracking quests and added the rep gained from them

**Pull request merged**
